name: baby_names
description: A Flutter Application that can suggest baby names and allow people to vote for their favorite name.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  cloud_firestore: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true